<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-01T22:47:41 EET" name="Default suite" finished-at="2023-12-01T22:47:50 EET" duration-ms="9514">
    <groups>
    </groups>
    <test started-at="2023-12-01T22:47:41 EET" name="Default test" finished-at="2023-12-01T22:47:50 EET" duration-ms="9514">
      <class name="tests.CreateTrueFalseItemTest">
        <test-method is-config="true" signature="startDriver(java.lang.String)[pri:0, instance:tests.CreateTrueFalseItemTest@1cf6d1be]" started-at="2023-12-01T22:47:36 EET" name="startDriver" finished-at="2023-12-01T22:47:41 EET" duration-ms="4488" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startDriver -->
        <test-method signature="registeredUserCanLoginSuccessfully()[pri:1, instance:tests.CreateTrueFalseItemTest@1cf6d1be]" started-at="2023-12-01T22:47:41 EET" name="registeredUserCanLoginSuccessfully" finished-at="2023-12-01T22:47:44 EET" duration-ms="3564" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registeredUserCanLoginSuccessfully -->
        <test-method is-config="true" signature="screenshotOnFailure(org.testng.ITestResult)[pri:0, instance:tests.CreateTrueFalseItemTest@1cf6d1be]" started-at="2023-12-01T22:47:44 EET" name="screenshotOnFailure" finished-at="2023-12-01T22:47:44 EET" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=registeredUserCanLoginSuccessfully status=SUCCESS method=CreateTrueFalseItemTest.registeredUserCanLoginSuccessfully()[pri:1, instance:tests.CreateTrueFalseItemTest@1cf6d1be] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshotOnFailure -->
        <test-method signature="UserSeeAllTFItems()[pri:2, instance:tests.CreateTrueFalseItemTest@1cf6d1be]" started-at="2023-12-01T22:47:44 EET" name="UserSeeAllTFItems" finished-at="2023-12-01T22:47:48 EET" duration-ms="4188" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UserSeeAllTFItems -->
        <test-method signature="UserCreateTrueFalseItem()[pri:3, instance:tests.CreateTrueFalseItemTest@1cf6d1be]" started-at="2023-12-01T22:47:48 EET" name="UserCreateTrueFalseItem" finished-at="2023-12-01T22:47:50 EET" duration-ms="1608" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at tests.CreateTrueFalseItemTest.UserCreateTrueFalseItem(CreateTrueFalseItemTest.java:50)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UserCreateTrueFalseItem -->
        <test-method is-config="true" signature="screenshotOnFailure(org.testng.ITestResult)[pri:0, instance:tests.CreateTrueFalseItemTest@1cf6d1be]" started-at="2023-12-01T22:47:48 EET" name="screenshotOnFailure" finished-at="2023-12-01T22:47:48 EET" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=UserSeeAllTFItems status=SUCCESS method=CreateTrueFalseItemTest.UserSeeAllTFItems()[pri:2, instance:tests.CreateTrueFalseItemTest@1cf6d1be] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshotOnFailure -->
        <test-method is-config="true" signature="screenshotOnFailure(org.testng.ITestResult)[pri:0, instance:tests.CreateTrueFalseItemTest@1cf6d1be]" started-at="2023-12-01T22:47:50 EET" name="screenshotOnFailure" finished-at="2023-12-01T22:47:50 EET" duration-ms="131" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=UserCreateTrueFalseItem status=FAILURE method=CreateTrueFalseItemTest.UserCreateTrueFalseItem()[pri:3, instance:tests.CreateTrueFalseItemTest@1cf6d1be] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshotOnFailure -->
        <test-method is-config="true" signature="stopDriver()[pri:0, instance:tests.CreateTrueFalseItemTest@1cf6d1be]" started-at="2023-12-01T22:47:50 EET" name="stopDriver" finished-at="2023-12-01T22:47:50 EET" duration-ms="136" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stopDriver -->
      </class> <!-- tests.CreateTrueFalseItemTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
